"""Core Pydantic models shared across modules."""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class Strategy(str, Enum):
    """Supported trading strategies."""

    DAYTRADE = "daytrade"
    SWING = "swing"
    POSITION = "position"
    LONGTERM = "longterm"
    DIVIDEND = "dividend"


class Action(str, Enum):
    """Supported recommendation actions."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    WATCH = "watch"


class OrderType(str, Enum):
    """Supported order types."""

    LIMIT = "limit"
    MARKET = "market"


class Quote(BaseModel):
    """Realtime quote snapshot."""

    symbol: str
    name: str
    price: Decimal
    open: Decimal
    high: Decimal
    low: Decimal
    prev_close: Decimal
    volume: int
    bid: Decimal
    ask: Decimal
    limit_up: Decimal
    limit_down: Decimal
    timestamp: datetime
    is_suspended: bool = False


class Position(BaseModel):
    """Single portfolio position."""

    symbol: str
    qty: int
    avg_cost: Decimal
    account_type: Literal["cash", "margin", "short"] = "cash"
    opened_at: date

    @property
    def cost_basis(self) -> Decimal:
        """Return the total acquisition cost of the position."""

        return self.avg_cost * self.qty


class Portfolio(BaseModel):
    """Portfolio snapshot."""

    cash: Decimal
    positions: list[Position]
    updated_at: datetime

    def total_cost(self) -> Decimal:
        """Return the total cost basis of all positions."""

        return sum((position.cost_basis for position in self.positions), Decimal("0"))


class TechnicalIndicators(BaseModel):
    """Technical indicator snapshot."""

    symbol: str
    ma5: Decimal | None = None
    ma20: Decimal | None = None
    ma60: Decimal | None = None
    kd_k: Decimal | None = None
    kd_d: Decimal | None = None
    macd: Decimal | None = None
    macd_signal: Decimal | None = None
    rsi14: Decimal | None = None
    bband_upper: Decimal | None = None
    bband_lower: Decimal | None = None
    volume_ratio: Decimal | None = None


class ChipData(BaseModel):
    """Chip and margin data snapshot."""

    symbol: str
    foreign_net: int
    trust_net: int
    dealer_net: int
    margin_balance: int
    short_balance: int
    date: date


class Recommendation(BaseModel):
    """Structured recommendation generated by AI."""

    symbol: str
    action: Action
    qty: int = Field(0, ge=0)
    order_type: OrderType = OrderType.LIMIT
    price: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    reason: str
    confidence: float = Field(ge=0.0, le=1.0)
    strategy: Strategy
    generated_at: datetime

    @field_validator("qty")
    @classmethod
    def check_qty_for_action(cls, value: int, info: object) -> int:
        """Require buy and sell recommendations to include a quantity."""

        action = info.data.get("action") if hasattr(info, "data") else None
        if action in (Action.BUY, Action.SELL) and value == 0:
            raise ValueError("buy/sell 必須指定 qty")
        return value


class AnalysisRequest(BaseModel):
    """AI analysis input payload."""

    strategy: Strategy
    portfolio: Portfolio
    quotes: dict[str, Quote]
    indicators: dict[str, TechnicalIndicators]
    chips: dict[str, ChipData]
    watchlist: list[str]
    risk_preference: Literal["conservative", "moderate", "aggressive"]
    max_position_pct: float = 0.2


class AnalysisResponse(BaseModel):
    """AI analysis output payload."""

    recommendations: list[Recommendation]
    market_view: str
    warnings: list[str] = Field(default_factory=list)
    raw_prompt_tokens: int = 0
    raw_completion_tokens: int = 0
